//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatamConnexDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string Gender { get; set; }
        public bool Active { get; set; }
    }
}
