//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatamConnexDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BooksEntities : DbContext
    {
        public BooksEntities()
            : base("name=BooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
    
        public virtual ObjectResult<spGetAllBooks_Result> spGetAllBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllBooks_Result>("spGetAllBooks");
        }
    
        public virtual ObjectResult<spGetBooksByAuthor_Result> spGetBooksByAuthor(Nullable<decimal> aUTHOR_ID)
        {
            var aUTHOR_IDParameter = aUTHOR_ID.HasValue ?
                new ObjectParameter("AUTHOR_ID", aUTHOR_ID) :
                new ObjectParameter("AUTHOR_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetBooksByAuthor_Result>("spGetBooksByAuthor", aUTHOR_IDParameter);
        }
    
        public virtual ObjectResult<spGetBooksByCategory_Result> spGetBooksByCategory(Nullable<decimal> cATEGORY_ID)
        {
            var cATEGORY_IDParameter = cATEGORY_ID.HasValue ?
                new ObjectParameter("CATEGORY_ID", cATEGORY_ID) :
                new ObjectParameter("CATEGORY_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetBooksByCategory_Result>("spGetBooksByCategory", cATEGORY_IDParameter);
        }
    }
}
